import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";

const kanit = Kanit({
  weight: ["300", "400", "500"],
  subsets: ["thai"],
  display: "swap",
  variable: "--font-kanit",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kanit.variable}`}>
        <div className="min-h-screen bg-[url('./assets/bg.jpg')] bg-cover bg-center">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
